# Question - 1

# 1. Write a function to compute 5/0 and use try/except to catch the exceptions



try:
    a = 5/0
except Exception as e:
    print(e)